export const AUTH_ROUTES = {
  LOGIN: "/login",
};

export const PROTECTED_ROUTES = {
  DASHBOARD: "/dashboard",
  CLASS_SESSIONS_LIST: "/class-sessions",
  CLASS_SESSIONS_DETAIL: "/class-sessions/:id",
  USERS_LIST: "/users",
  USERS_DETAIL: "/users/:id",
  USERS_EDIT: "/users/:id/edit",
  TEACHERS_LIST: "/teachers",
  TEACHERS_DETAIL: "/teachers/:id",
  TEACHERS_EDIT: "/teachers/:id/edit",
  STUDENTS_LIST: "/students",
  STUDENTS_DETAIL: "/students/:id",
  STUDENTS_EDIT: "/students/:id/edit",
  CLASSES_LIST: "/classes",
  CLASSES_DETAIL: "/classes/:id",
  ATTENDANCE_LIST: "/attendance",
  ATTENDANCE_DETAIL: "/attendance/:id",
  ATTENDANCE_TRACKER: "/tracker",
  ORDERS_LIST: "/orders",
  CHANGE_PASSWORD: "/change-password",
  MY_CLASSES: "/my-classes",
  MY_SCHEDULE: "/my-schedule",
  MY_ATTENDANCE: "/my-attendance",
  MY_STUDENTS: "/my-students",
  MY_CLASSES_TEACHER: "/my-teaching-classes",
};
